---
# Source: helm for kubernetes/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: springooooooboot
  labels:
    app: springooooooboot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springooooooboot
  template:
    metadata:
      labels:
        app: springooooooboot
    spec:
      containers:
        - name: springooooooboot
          image: docker.io/phengbunath/springooooooboot:1
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
